project:
  type: website

website:
  title: "lab2_datascience_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - solar
      - brand
    css: styles.css

execute: 
  freeze:  auto



